### ISSUE TITLE
Create 'upstream' branch to track original repo

### ISSUE THREAD

**Issue by krbullock** [VirtaHealth/fhir#2]
I'd like to propose a branching strategy for this repo in which we:

* Set an `upstream` branch that tracks Google's `master` branch
* Our `master` branch continues to include our changes
* To update from upstream, `git pull --rebase https://github.com/google/fhir.git master:upstream`

@tmc @sam-virta thoughts?

**Comment by sam-virta** [comment]
Sounds good to me @krbullock !

**Comment by krbullock** [comment]
Funny story, we already have an `upstream` branch. Will update that and add a note in the README
